-- 1. 온라인 판매 데이터 추출
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

-- 2. 오프라인 판매 데이터 추출 (USER_ID 자리에 NULL 삽입)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

-- 3. 합쳐진 전체 데이터 정렬
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;